application: ante
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: home.app

- url: /index\.html
  script: home.app

- url: /bootstrap-3.4.1-dist
  static_dir: bootstrap-3.4.1-dist

- url: /mycss
  static_dir: mycss
  
- url: /schoolmap
  static_dir: schoolmap


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
